<div class="loadingio-spinner-spinner-z9oicxosv6">
  <div class="ldio-5ohokaigrds">
    <div />
    <div />
    <div />
    <div />
    <div />
    <div />
    <div />
    <div />
    <div />
    <div />
    <div />
    <div />
  </div>
</div>

<style type="text/css">
  @keyframes ldio-5ohokaigrds {
    0% {
      opacity: 1;
    }
    100% {
      opacity: 0;
    }
  }
  .ldio-5ohokaigrds div {
    left: 47px;
    top: 24px;
    position: absolute;
    animation: ldio-5ohokaigrds linear 1s infinite;
    background: #93dbe9;
    width: 6px;
    height: 12px;
    border-radius: 3px / 6px;
    transform-origin: 3px 26px;
  }
  .ldio-5ohokaigrds div:nth-child(1) {
    transform: rotate(0deg);
    animation-delay: -0.9166666666666666s;
    background: #93dbe9;
  }
  .ldio-5ohokaigrds div:nth-child(2) {
    transform: rotate(30deg);
    animation-delay: -0.8333333333333334s;
    background: #93dbe9;
  }
  .ldio-5ohokaigrds div:nth-child(3) {
    transform: rotate(60deg);
    animation-delay: -0.75s;
    background: #93dbe9;
  }
  .ldio-5ohokaigrds div:nth-child(4) {
    transform: rotate(90deg);
    animation-delay: -0.6666666666666666s;
    background: #93dbe9;
  }
  .ldio-5ohokaigrds div:nth-child(5) {
    transform: rotate(120deg);
    animation-delay: -0.5833333333333334s;
    background: #93dbe9;
  }
  .ldio-5ohokaigrds div:nth-child(6) {
    transform: rotate(150deg);
    animation-delay: -0.5s;
    background: #93dbe9;
  }
  .ldio-5ohokaigrds div:nth-child(7) {
    transform: rotate(180deg);
    animation-delay: -0.4166666666666667s;
    background: #93dbe9;
  }
  .ldio-5ohokaigrds div:nth-child(8) {
    transform: rotate(210deg);
    animation-delay: -0.3333333333333333s;
    background: #93dbe9;
  }
  .ldio-5ohokaigrds div:nth-child(9) {
    transform: rotate(240deg);
    animation-delay: -0.25s;
    background: #93dbe9;
  }
  .ldio-5ohokaigrds div:nth-child(10) {
    transform: rotate(270deg);
    animation-delay: -0.16666666666666666s;
    background: #93dbe9;
  }
  .ldio-5ohokaigrds div:nth-child(11) {
    transform: rotate(300deg);
    animation-delay: -0.08333333333333333s;
    background: #93dbe9;
  }
  .ldio-5ohokaigrds div:nth-child(12) {
    transform: rotate(330deg);
    animation-delay: 0s;
    background: #93dbe9;
  }
  .loadingio-spinner-spinner-z9oicxosv6 {
    width: 61px;
    height: 61px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-5ohokaigrds {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(0.61);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-5ohokaigrds div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
</style>
